backend:
    name: git-gateway
    branch: master

media_folder: "static/uploads"
public_folder: "uploads"

collections:
    - name: "drop-blog"
      label: "DropBlog"
      folder: "src/posts/drop-blog"
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      fields:
        - {label: "1. Add a title", name: "title", widget: "string", required: true}
        - {label: "Content Type", name: "contentType", widget: "hidden", default: "blog_post"}
        - {label: "2. Add posts main,big image", name: "postCardImage", widget: image, required: false}
        - {label: "3. Date you publising", name: "date", widget: "date"}
        - label: "4. You must select one topic category"
          name: "category"
          widget: "select"
          options: ["Ideas", "Galaxy Fun", "About Me", "Espionage", "Tips&Tricks", "Ship Designs", "Station Design", "Galaxy War", "Special Event"]
        - {label: 5. Your nickname as an Author, name: author, widget: "string", default: Dropper}
        - {label: Author Image, name: authorImage, widget: image, default: "uploads/drop-logo1.png", required: false}
        - {label: Type, name: type, widget: hidden, default: "post"}
        - {label: "6. Now write your post, to add images tap on '+' button below", name: "body", widget: "markdown"}
