backend:
    name: git-gateway
    branch: master

media_folder: "static/uploads"
public_folder: "uploads"

collections:
    - name: "drop-blog"
      label: "DropBlog"
      folder: "src/posts/drop-blog"
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      fields:
        - {label: "Title", name: "title", widget: "string", required: true}
        - {label: "Content Type", name: "contentType", widget: "hidden", default: "blog_post"}
        - {label: "PostCardImage", name: "postCardImage", widget: image, required: false}
        - {label: "Publish Date", name: "date", widget: "date"}
        - {label: "Align Content", name: "align", widget: "select", options: ["Espionage", "Tips&Tricks, "Ideas", "Ship Builds", "Station Builds","About Us", "Galaxy War", "Galaxy Fun"], required: true}
        - {label: "Tags", name: "tags", widget: "list", required: false}
        - {label: Author, name: author, widget: hidden, default: Chris Stayte}
        - {label: Author Image, name: authorImage, widget: image, default: "uploads/drop-logo1.png", required: false}
        - {label: Commenting, name: comments, widget: boolean, default: true}
        - {label: Sharing, name: share, widget: boolean, default: true}
        - {label: Type, name: type, widget: hidden, default: "post"}
        - {label: "Body", name: "body", widget: "markdown"}
    - name: "life"
      label: "Life Post"
      folder: "src/posts/life"
      create: true
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "date"}
        - {label: "Content Type", name: "contentType", widget: "hidden", default: "life"}
        - {label: "Path", name: "path", widget: "hidden", default: "/life"}
        - {label: "PostCardImage", name: "postCardImage", widget: image, required: false}
        - {label: "PostCardImageUrl", name: "postCardImageUrl", widget: 'string', required: false}
        - {label: "Draft", name: "draft", widget: "boolean", default: true}
        - {label: "Categories", name: "categories", widget: "string", required: true}
        - {label: "Tags", name: "tags", widget: "list", required: false}
        - {label: Author, name: author, widget: hidden, default: Chris Stayte}
        - {label: Author Image, name: authorImage, widget: hidden, default: "uploads/admirals.jpg"}
        - {label: "Header Image", name: image, widget: image, required: false}
        - {label: Commenting, name: comments, widget: boolean, default: true}
        - {label: Sharing, name: share, widget: boolean, default: true}
        - {label: Type, name: type, widget: hidden, default: "post"}
        - {label: "Body", name: "body", widget: "markdown"}
